In [1]:
from pathlib import Path
from collections import Counter
from PIL import Image
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
CSV_PATH = Path("Dhan-Shomadhan/Dhan-Shomadhan_picture_Information.csv")

df = pd.read_csv(CSV_PATH)

print(df.shape)
print(df.columns.tolist())
print(df.info())
display(df.head())

(1106, 3)
['Unnamed: 0', 'pictureName', 'Diseases']
<class 'pandas.DataFrame'>
RangeIndex: 1106 entries, 0 to 1105
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   1106 non-null   int64
 1   pictureName  1106 non-null   str
 2   Diseases     1106 non-null   str
dtypes: int64(1), str(2)
memory usage: 26.1 KB
None

   Unnamed: 0 pictureName                       Diseases
0           0   bsf_0.jpg  Browon Spot(Feild Background)
1           1   bsf_1.jpg  Browon Spot(Feild Background)
2           2  bsf_10.jpg  Browon Spot(Feild Background)
3           3  bsf_11.jpg  Browon Spot(Feild Background)
4           4  bsf_12.jpg  Browon Spot(Feild Background)

In [8]:
print(df["Diseases"].value_counts())

Diseases
Shath Blight(white Background)     219
Rice Blast(white Background)       198
Leaf Scaled(white Background)      143
Rice Tungro(white Background)      119
Brown Spot(white Background)        90
Rice Turgro(Feild Background)       76
Leaf Scaled(Feild Background)       74
Rice Blast(Feild Background)        74
Sheath Blight(Feild Background)     64
Browon Spot(Feild Background)       49
Name: count, dtype: int64

In [ ]:
label_mapping = {
    "Shath Blight(white Background)": ("Sheath Blight", "white"),
    "Rice Blast(white Background)": ("Rice Blast", "white"),
    "Leaf Scaled(white Background)": ("Leaf Scald", "white"),
    "Rice Tungro(white Background)": ("Rice Tungro", "white"),
    "Brown Spot(white Background)": ("Brown Spot", "white"),
    
    "Rice Turgro(Feild Background)": ("Rice Tungro", "field"),
    "Leaf Scaled(Feild Background)": ("Leaf Scald", "field"),
    "Rice Blast(Feild Background)": ("Rice Blast", "field"),
    "Sheath Blight(Feild Background)": ("Sheath Blight", "field"),
    "Browon Spot(Feild Background)": ("Brown Spot", "field"),
}

df[["class", "domain"]] = pd.DataFrame(
    df["Diseases"]
    .map(lambda value: label_mapping.get(value, (None, None)))
    .tolist(),
    index=df.index,
    columns=["class", "domain"],
)

In [11]:
diseases = ['Browon Spot', 'Leaf Scaled', 'Rice Blast', 'Rice Turgro', 'Sheahth Blight']
background = ["White Background", 'Field Background']

In [16]:
df["Background"] = df["Diseases"].apply(lambda x: "white" if "white" in x else "field")
df[:50]

    Unnamed: 0 pictureName                       Diseases Background
0            0   bsf_0.jpg  Browon Spot(Feild Background)      field
1            1   bsf_1.jpg  Browon Spot(Feild Background)      field
2            2  bsf_10.jpg  Browon Spot(Feild Background)      field
3            3  bsf_11.jpg  Browon Spot(Feild Background)      field
4            4  bsf_12.jpg  Browon Spot(Feild Background)      field
5            5  bsf_13.jpg  Browon Spot(Feild Background)      field
6            6  bsf_14.jpg  Browon Spot(Feild Background)      field
7            7  bsf_15.jpg  Browon Spot(Feild Background)      field
8            8  bsf_16.jpg  Browon Spot(Feild Background)      field
9            9  bsf_17.jpg  Browon Spot(Feild Background)      field
10          10  bsf_18.jpg  Browon Spot(Feild Background)      field
11          11  bsf_19.jpg  Browon Spot(Feild Background)      field
12          12   bsf_2.jpg  Browon Spot(Feild Background)      field
13          13  bsf_20.jpg  Browon Spot(Feild Background)      field
14          14  bsf_21.jpg  Browon Spot(Feild Background)      field
15          15  bsf_22.jpg  Browon Spot(Feild Background)      field
16          16  bsf_23.jpg  Browon Spot(Feild Background)      field
17          17  bsf_24.jpg  Browon Spot(Feild Background)      field
18          18  bsf_25.jpg  Browon Spot(Feild Background)      field
19          19  bsf_26.jpg  Browon Spot(Feild Background)      field
20          20  bsf_27.jpg  Browon Spot(Feild Background)      field
21          21  bsf_28.jpg  Browon Spot(Feild Background)      field
22          22  bsf_29.jpg  Browon Spot(Feild Background)      field
23          23   bsf_3.jpg  Browon Spot(Feild Background)      field
24          24  bsf_30.jpg  Browon Spot(Feild Background)      field
25          25  bsf_31.jpg  Browon Spot(Feild Background)      field
26          26  bsf_32.jpg  Browon Spot(Feild Background)      field
27          27  bsf_33.jpg  Browon Spot(Feild Background)      field
28          28  bsf_34.jpg  Browon Spot(Feild Background)      field
29          29  bsf_35.jpg  Browon Spot(Feild Background)      field
30          30  bsf_36.jpg  Browon Spot(Feild Background)      field
31          31  bsf_37.jpg  Browon Spot(Feild Background)      field
32          32  bsf_38.jpg  Browon Spot(Feild Background)      field
33          33  bsf_39.jpg  Browon Spot(Feild Background)      field
34          34   bsf_4.jpg  Browon Spot(Feild Background)      field
35          35  bsf_40.jpg  Browon Spot(Feild Background)      field
36          36  bsf_41.jpg  Browon Spot(Feild Background)      field
37          37  bsf_42.jpg  Browon Spot(Feild Background)      field
38          38  bsf_43.jpg  Browon Spot(Feild Background)      field
39          39  bsf_44.jpg  Browon Spot(Feild Background)      field
40          40  bsf_45.jpg  Browon Spot(Feild Background)      field
41          41  bsf_46.jpg  Browon Spot(Feild Background)      field
42          42  bsf_47.jpg  Browon Spot(Feild Background)      field
43          43  bsf_48.jpg  Browon Spot(Feild Background)      field
44          44   bsf_5.jpg  Browon Spot(Feild Background)      field
45          45   bsf_6.jpg  Browon Spot(Feild Background)      field
46          46   bsf_7.jpg  Browon Spot(Feild Background)      field
47          47   bsf_8.jpg  Browon Spot(Feild Background)      field
48          48   bsf_9.jpg  Browon Spot(Feild Background)      field
49          49   lsf_0.jpg  Leaf Scaled(Feild Background)      field

In [14]:
results = {}

for background in background:
    for disease in diseases:
        results[f"{background} - {disease}"] = df["Diseases"]

KeyError: 'Background'